server:
  port: 8097

zuul:
  sensitiveHeaders:
  routes:
    reports:
      url: http://rest:8081/reports
    tasks:
      url: http://rest:8081/tasks
    users:
      url: http://rest:8081/users
    projects:
      url: http://rest:8081/projects
    groups:
      url: http://rest:8081/groups
    configs:
      url: http://rest:8081/configs
    logs:
      url: http://rest:8081/logs
    excel:
      url: http://rest:8081/excel


eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/
    instance:
      preferIpAddress: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.elinext.com/.well-known/openid-configuration/jwks

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
